### ISSUE TITLE
Schmuck don't recognize Unearthed ores.

### ISSUE THREAD

**Issue by JumperREDACTED** [rwilliaise/schmucks#2]
**Description**
Schmucks don't recognize ores in other stone variants from the mod Unearthed.

**Expected behavior**
They should go to them and mine them like regular ores.

**Screenshots**

**Log**
If you can, please attach a log as well. This will make the process a lot faster.

**Desktop (please complete the following information):**
 - OS: W10
 - Java Version: Java 8
 - Version: 1.2.0
 - Minecraft Version: 1.16.5
 - Sodium installed: yes
 - Other mods: a lot, but probably not relevant

**Comment by rwilliaise** [comment]
I have no idea why this doesn't work. It's gonna take me a few days to sort this out - sorry!
