### ISSUE TITLE
Server crashes when players hits another player with active schmucks

### ISSUE THREAD

**Issue by cdaise** [rwilliaise/schmucks#5]
**Description**
When you have active schmucks running around, hitting another player seems to crash the server.

**To Reproduce**
0. Play on a server with other players
1. Have some active Schmucks running around in the game
2. Hit another player
3. Server crashes

**Expected behavior**
Server should not crash when you hit a player. They should just normally start attacking the player if PVP is on.

**Desktop (please complete the following information):**
 - OS: Widows 10
 - Java Version: Java 16
 - Version: 1.4.0
 - Minecraft Version: 1.17
 - Sodium installed: no
 - Other mods: None
By default, Java 8 is bundled along with Minecraft <=1.16.5. However, with 1.17, it is now Java 16.

**Additional context**

**Comment by kotx** [comment]
I'm having the same problem. Server log is attached.
[crash.txt](https://github.com/rwilliaise/schmucks/files/6834008/crash.txt)

**Comment by rwilliaise** [comment]
This has been fixed - sorry about that. The update should be published by Sunday-Monday.
